### ISSUE TITLE
Kodi 19.0 Matrix | Not working due to Python version

### ISSUE THREAD

**Issue by vexersa** [AddonScriptorDE/plugin.video.bestofyoutube_com#7]
Thanks for the awesome plugin. I enjoy using it daily, however now that I've updated my Kodi to Kodi 19, the plugin no longer works. 

This looks to be to do with Kodi 19 only using Python 3. 

Is there any way you can update the plugin? I'd be happy to help bug fix if possible!

I've attempted to use a Python 2 to Python 3 translator and updated references in the addon.xml to python 3, but no dice. 

Errors I receive are type errors it looks like, see below!

 ```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'iconImage' is an invalid keyword argument for this function
                                                   Traceback (most recent call last):
                                                     File "/home/andrew/.kodi/addons/plugin.video.bestofyoutube_com/default.py", line 166, in <module>
                                                       index()
                                                     File "/home/andrew/.kodi/addons/plugin.video.bestofyoutube_com/default.py", line 28, in index
                                                       addDir(translation(30001), urlMain, "listVideos", icon)
                                                     File "/home/andrew/.kodi/addons/plugin.video.bestofyoutube_com/default.py", line 136, in addDir
                                                       liz = xbmcgui.ListItem(name, iconImage="DefaultFolder.png", thumbnailImage=iconimage)
                                                   TypeError: 'iconImage' is an invalid keyword argument for this function
                                                   -->End of Python script error report<--

```

**Comment by Shtucer** [comment]
@vexersa If you still interested on update, check out my fork.

**Comment by vexersa** [comment]
@Shtucer 

Thank you very much! I was actually in the process of refactoring the code myself so your fork came at a great time 🙏
